// F0853: Analytics export PDF
import { NextRequest, NextResponse } from 'next/server'
import PDFDocument from 'pdfkit'
import { supabaseAdmin } from '@/lib/supabase'

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const dateFrom = searchParams.get('dateFrom')
    const dateTo = searchParams.get('dateTo')

    // Default to last 30 days
    const defaultDateFrom = new Date()
    defaultDateFrom.setDate(defaultDateFrom.getDate() - 30)

    const startDate = dateFrom ? new Date(dateFrom) : defaultDateFrom
    const endDate = dateTo ? new Date(dateTo) : new Date()

    // Fetch analytics data
    const { data: calls, error: callsError } = await supabaseAdmin
      .from('voice_agent_calls')
      .select('id, outcome, status, duration, sentiment, created_at')
      .gte('created_at', startDate.toISOString())
      .lte('created_at', endDate.toISOString())

    if (callsError) {
      return NextResponse.json({ error: callsError.message }, { status: 500 })
    }

    const { data: bookings, error: bookingsError } = await supabaseAdmin
      .from('voice_agent_bookings')
      .select('id, created_at')
      .gte('created_at', startDate.toISOString())
      .lte('created_at', endDate.toISOString())

    if (bookingsError) {
      return NextResponse.json({ error: bookingsError.message }, { status: 500 })
    }

    // Calculate metrics
    const totalCalls = calls.length
    const totalBookings = bookings.length
    const conversionRate = totalCalls > 0 ? ((totalBookings / totalCalls) * 100).toFixed(1) : '0.0'

    const successfulCalls = calls.filter((c) => c.outcome === 'success').length
    const failedCalls = calls.filter((c) => c.outcome === 'failed').length
    const avgDuration = calls.length > 0
      ? (calls.reduce((sum, c) => sum + (c.duration || 0), 0) / calls.length / 60).toFixed(1)
      : '0.0'

    const sentimentCounts = calls.reduce((acc, c) => {
      const sentiment = c.sentiment || 'neutral'
      acc[sentiment] = (acc[sentiment] || 0) + 1
      return acc
    }, {} as Record<string, number>)

    // Create PDF
    const doc = new PDFDocument({ size: 'A4', margin: 50 })
    const chunks: Buffer[] = []

    doc.on('data', (chunk) => chunks.push(chunk))

    // PDF Content
    doc.fontSize(20).text('Voice AI Agent Analytics Report', { align: 'center' })
    doc.moveDown()

    doc.fontSize(12).text(`Report Period: ${startDate.toLocaleDateString()} - ${endDate.toLocaleDateString()}`, { align: 'center' })
    doc.text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' })
    doc.moveDown(2)

    // Summary Section
    doc.fontSize(16).text('Summary', { underline: true })
    doc.moveDown()

    doc.fontSize(12)
    doc.text(`Total Calls: ${totalCalls}`)
    doc.text(`Total Bookings: ${totalBookings}`)
    doc.text(`Booking Conversion Rate: ${conversionRate}%`)
    doc.text(`Average Call Duration: ${avgDuration} minutes`)
    doc.moveDown()

    // Call Outcomes
    doc.fontSize(16).text('Call Outcomes', { underline: true })
    doc.moveDown()

    doc.fontSize(12)
    doc.text(`Successful: ${successfulCalls} (${totalCalls > 0 ? ((successfulCalls / totalCalls) * 100).toFixed(1) : 0}%)`)
    doc.text(`Failed: ${failedCalls} (${totalCalls > 0 ? ((failedCalls / totalCalls) * 100).toFixed(1) : 0}%)`)
    doc.moveDown()

    // Sentiment Analysis
    doc.fontSize(16).text('Sentiment Analysis', { underline: true })
    doc.moveDown()

    doc.fontSize(12)
    Object.entries(sentimentCounts).forEach(([sentiment, count]) => {
      const percentage = totalCalls > 0 ? ((count / totalCalls) * 100).toFixed(1) : '0.0'
      doc.text(`${sentiment.charAt(0).toUpperCase() + sentiment.slice(1)}: ${count} (${percentage}%)`)
    })
    doc.moveDown()

    // Call Volume by Day
    doc.fontSize(16).text('Call Volume by Day', { underline: true })
    doc.moveDown()

    const callsByDay = calls.reduce((acc, c) => {
      const day = new Date(c.created_at).toLocaleDateString()
      acc[day] = (acc[day] || 0) + 1
      return acc
    }, {} as Record<string, number>)

    doc.fontSize(12)
    const sortedDays = Object.entries(callsByDay).sort((a, b) => new Date(a[0]).getTime() - new Date(b[0]).getTime())
    sortedDays.slice(0, 10).forEach(([day, count]) => {
      doc.text(`${day}: ${count} calls`)
    })

    if (sortedDays.length > 10) {
      doc.text(`... and ${sortedDays.length - 10} more days`)
    }

    doc.moveDown(2)

    // Footer
    doc.fillColor('#666666').fontSize(10).text(
      'Generated by Voice AI Agent Analytics System',
      { align: 'center' }
    )

    doc.end()

    // Wait for PDF generation to complete
    await new Promise((resolve) => doc.on('end', resolve))

    const pdfBuffer = Buffer.concat(chunks)

    // Return PDF
    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="analytics-report-${startDate.toISOString().split('T')[0]}-to-${endDate.toISOString().split('T')[0]}.pdf"`,
      },
    })
  } catch (error: any) {
    console.error('[GET /api/analytics/export/pdf] Error:', error)
    return NextResponse.json(
      { error: error.message || 'Failed to generate PDF' },
      { status: 500 }
    )
  }
}
